// Generates src/detection/decimal-digit-zeros.ts: the code point of digit
// zero for every block of ten decimal digits (\p{Nd}) that this Node's
// Unicode data knows about.
//
// Run with `npm run gen:digits` after a Node upgrade if the decimal-digit
// test says the table is out of date.
//
// Unicode guarantees that decimal digits are assigned in contiguous runs of
// 0-9 in ascending order (Unicode Stability Policy, Numeric_Type=Decimal).
// A run can hold several blocks back to back (the mathematical digits
// U+1D7CE-U+1D7FF are five), so a new block starts every ten code points.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const DECIMAL_DIGIT = /^\p{Nd}$/u;
const MAX_CODE_POINT = 0x10ffff;
const OUT_FILE = new URL('../src/detection/decimal-digit-zeros.ts', import.meta.url);

const zeros: number[] = [];
let runStart = -1;
for (let cp = 0; cp <= MAX_CODE_POINT; cp++) {
  if (!DECIMAL_DIGIT.test(String.fromCodePoint(cp))) {
    runStart = -1;
    continue;
  }
  if (runStart === -1) runStart = cp;
  if ((cp - runStart) % 10 === 0) zeros.push(cp);
}

const hex = (cp: number): string => `0x${cp.toString(16).padStart(4, '0')}`;
const source = `// GENERATED by scripts/generate-decimal-digit-zeros.ts. Do not edit by hand.
// Unicode ${process.versions.unicode} (Node ${process.versions.node}, ICU ${process.versions.icu}).
//
// The code point of digit zero for every block of ten decimal digits (\\p{Nd}),
// in ascending order. Digit d of a block is zero + d.

export const DECIMAL_DIGIT_ZEROS: readonly number[] = [
  ${zeros.map(hex).join(', ')},
];
`;

writeFileSync(OUT_FILE, source);
console.log(`Wrote ${zeros.length} blocks to ${fileURLToPath(OUT_FILE)}`);
