// Generates src/detection/decimal-digit-zeros.ts: the code point of digit
// zero for every block of ten decimal digits (\p{Nd}) that this Node's
// Unicode data knows about.
//
// Run with `npm run gen:digits` on the Node in .nvmrc after changing it, or
// on any newer Node whose Unicode knows digits the table lacks; the
// decimal-digit test says when. It refuses to run on a Node with an older
// Unicode than the table's (bug-log 44): that would drop blocks the newer
// Unicode added, and their digits would then reach the detectors unmapped.
//
// Unicode guarantees that decimal digits are assigned in contiguous runs of
// 0-9 in ascending order (Unicode Stability Policy, Numeric_Type=Decimal).
// A run can hold several blocks back to back (the mathematical digits
// U+1D7CE-U+1D7FF are five), so a new block starts every ten code points.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { DECIMAL_DIGIT_UNICODE } from '../src/detection/decimal-digit-zeros.js';

const DECIMAL_DIGIT = /^\p{Nd}$/u;
const MAX_CODE_POINT = 0x10ffff;
const OUT_FILE = new URL('../src/detection/decimal-digit-zeros.ts', import.meta.url);

/** Negative when Unicode version a is older than b ("16.0" < "17.0"). */
const compareVersions = (a: string, b: string): number => {
  const [x, y] = [a, b].map((v) => v.split('.').map(Number));
  for (let i = 0; i < Math.max(x!.length, y!.length); i++) {
    const d = (x![i] ?? 0) - (y![i] ?? 0);
    if (d !== 0) return d;
  }
  return 0;
};

const unicode = process.versions.unicode!;
if (compareVersions(unicode, DECIMAL_DIGIT_UNICODE) < 0) {
  console.error(
    `Refusing to regenerate: the table is from Unicode ${DECIMAL_DIGIT_UNICODE}, this Node has ${unicode}. ` +
      'Run it on the Node in .nvmrc.',
  );
  process.exit(1);
}

const zeros: number[] = [];
let runStart = -1;
for (let cp = 0; cp <= MAX_CODE_POINT; cp++) {
  if (!DECIMAL_DIGIT.test(String.fromCodePoint(cp))) {
    runStart = -1;
    continue;
  }
  if (runStart === -1) runStart = cp;
  if ((cp - runStart) % 10 === 0) zeros.push(cp);
}

const hex = (cp: number): string => `0x${cp.toString(16).padStart(4, '0')}`;
const source = `// GENERATED by scripts/generate-decimal-digit-zeros.ts. Do not edit by hand.
// Unicode ${unicode} (Node ${process.versions.node}, ICU ${process.versions.icu}).
//
// The code point of digit zero for every block of ten decimal digits (\\p{Nd}),
// in ascending order. Digit d of a block is zero + d.

/** The Unicode version the table was generated from. */
export const DECIMAL_DIGIT_UNICODE = '${unicode}';

export const DECIMAL_DIGIT_ZEROS: readonly number[] = [
  ${zeros.map(hex).join(', ')},
];
`;

writeFileSync(OUT_FILE, source);
console.log(`Wrote ${zeros.length} blocks to ${fileURLToPath(OUT_FILE)}`);
